version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5435
      - DJANGO_DB_NAME=test
      - DJANGO_DB_USERNAME=test
      - DJANGO_DB_PASSWORD=test
    ports:
      - "8000:8000"
    command:
      - python manage.py runserver 0:8000
    volumes:
      - ./:/app/
